#!/bin/sh

### BEGIN INIT INFO
# Provides:     mongodb
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description: mongodb
# Description: mongo db server
### END INIT INFO

. /lib/lsb/init-functions

PROGRAM="/opt/mongodb/bin/mongod"
CONFIGFILE="/etc/mongodb.conf"
DBPATH="/data/mongodb"
LOCKFILE="$DBPATH/mongod.lock"
LOGFILE="$DBPATH/mongodb.log"
DAEMONUSER="mongod"

test -x $PROGRAM || exit 0

start () {
    log_begin_msg "Starting MongoDB server"
    start-stop-daemon --background --start --quiet \
        --chuid $DAEMONUSER:$DAEMONUSER \
        --exec $PROGRAM -- --config $CONFIGFILE
    errcode=$?
    log_end_msg $errcode
    return $errcode
}

stop () {
    if [ -z $( pidof mongod) ] ; then
        log_warning_msg "MongoDB not running, nothing to stop"
    else
        log_begin_msg "Stopping MongoDB server"
        start-stop-daemon --stop --quiet --exec $PROGRAM
        errcode=$?
        [ $errcode -eq 0 ] && rm -f $LOCKFILE
        log_end_msg $errcode
        return $errcode
    fi
}

status () {
    status_of_proc $PROGRAM
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        log_success_msg "Usage: /etc/init.d/mongodb {start|stop|restart|status}"
        exit 1
esac

exit 0